title: VISions of the Future Sustainable Practices within Visualization and Physicalization
logo: 
description: IEEE VIS 2024 Workshop
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
